### PR TITLE
FCS_FILENAME correction

### PR DESCRIPTION
**Pull request by jryurkanin**
#### Rationale
[ticket](https://www.labkey.org/McElrath/Support%20Tickets/issues-details.view?issueId=48473)
* client requested that all their queries use the $FCS parameter for the FCS_FILENAME field. This was originally not occurring in some instances because the $FCS may be an integer, which causes labkey to display the next field in the A._well lookup instead of the $FCS parameter value.

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Comment by jryurkanin** [comment]
@labkey-jony Steve asked me to implement the change in AP060 to all his AP queries. Before I do that, can you take a look at the SQL and let me know if I should be doing it differently? Seems simple enough, but I want to check before spending a while changing all 60 queries.

Realistically, this change only needs to be applied to a subset of his queries, but I would rather his AP queries uniformly define the FCS_FILENAME field.

**Comment by jryurkanin** [comment]
I decided to just update a few key APs that Steve mentioned.

**Comment by labkey-jony** [comment]
I added @labkey-matthewb to the reviewers since he would know for sure.

The changes look okay to me, but this is something completely new for me, so I'm not the right person to put a stamp of approval on this. But if Steve managed to test it out and confirm things, I think that's good enough.

**Review by labkey-jony — APPROVED** [review]

**Comment by jryurkanin** [comment]
josh took a look at it and thought it was okay too. there are edge-case scenarios that could cause problems, but they are highly improbable.

**Pull request merged**
